export const GET_WORKSPACE_DATA = "GET_WORKSPACE_DATA";
export const ADD_WORKSPACE_DATA ="ADD_WORKSPACE_DATA";
export const DELETE_WORKSPACE_DATA="DELETE_WORKSPACE_DATA";
export const EDIT_WORKSPACE_DATA="EDIT_WORKSPACE_DATA";

export const GET_CARD ="GET_CARD";
export const ADD_CARD ="ADD_CARD";
export const DELETE_CARD ="DELETE_CARD";
export const EDIT_CARD ="EDIT_CARD";
